### ISSUE TITLE
Craft pictures not appearing

### ISSUE THREAD

**Issue by 01brhodes** [Sujimichi/KerbalX#26]
I have uploaded multiple craft before and after the kerbalx update. Of the new ones, when I upload images for some of them (or rather, upload the Images to TAPEGaming's discord server and copy the image address, then put the image address into the craft page) work as they did previously (they work). For some other craft that I upload, the images only appear once you click on the craft. Otherwise, there is no public thumbnail. If I edit the craft page and add another identical image address, the problem is fixed temporarily. (about a minute, no longer). Note that none of these new craft have unrecognized parts, and they are all modded ksp 1.3 craft.

![image](https://user-images.githubusercontent.com/32316655/30892063-936d78e6-a304-11e7-9223-ef5f7591e92f.png)

![image](https://user-images.githubusercontent.com/32316655/30892077-a856025a-a304-11e7-9387-4a502f5a6aef.png)

**Comment by Sujimichi** [comment]
Thanks for pointing this out. I have found an issue that might be causing this, but I need to investigate further. but meanwhile, I've fixed the thumbnails on those three craft so they are displaying thumbnails now.   If you add other craft and get the same issue, before I've found a proper fix for this, just add a comment here with a link to them and i'll sort them out.

**Comment by 01brhodes** [comment]
Thank you for investigating and fixing the thumbnails. I'll let you know of any further craft that I upload
(I upload frequently, so you may want to do them in chunks)

**Comment by 01brhodes** [comment]
I have now uploaded a craft using the kerbalx mod, which does not allow you to upload craft without taking a screenshot or uploading an image url. I screenshoted via the kerbalx mod, and uploaded my craft. I went to see it on kerbalx, and i recieved this message:
![image](https://user-images.githubusercontent.com/32316655/30937709-98f3008c-a3a5-11e7-94d4-a4b49dd0c3a0.png)

**Comment by Sujimichi** [comment]
I've made a change which fixes one obvious issue which might have been the cause of the issue you're experiencing. But I'm not 100% sure if the thing I fixed was the cause of the issue, or a by-product of it. Unfortunately I can't replicate the issue you're having exactly so it's hard to pin-down what's going on.  But this might solve it. Let me know if you're still getting the issue with thumbnails. 

[Pivotal Tracker Link](https://www.pivotaltracker.com/story/show/151482827)

**Comment by 01brhodes** [comment]
same exact problem with my recently uploaded tank 41 craft. uploaded without kerbalx mod.
https://kerbalx.com/01brhodes/craft
![image](https://user-images.githubusercontent.com/32316655/31104376-9f58a162-a7aa-11e7-8d49-ac26e0c70bca.png)
![image](https://user-images.githubusercontent.com/32316655/31104393-b8645034-a7aa-11e7-990b-2ac18bee3d13.png)

**Comment by 01brhodes** [comment]
problem magically fixed itself... i'll keep you posted.

**Comment by 01brhodes** [comment]
same story. https://kerbalx.com/01brhodes/tank-38s - problem did not fix itself. no kerbalx mod used.

**Comment by Sujimichi** [comment]
I know this might be a hassle, but on your next upload, can you try posting the image to a different site, like imgur? I just want to see if that makes a difference, and if so will give me a clue as to where the problem is occurring.

**Comment by Sujimichi** [comment]
I've fixed the thumbnail on tank-38s. I'm really mystified, I didn't do anything extra to make it work, just told it to set the image automatically from the page content (which is what happens when you save anyway) and it worked. So for some reason, it's either failing to call that process (which seems unlikely as other users don't seem to be having this issue), or when it gets called it is unable to fetch the image from the source site (partly why I'd like you to try a different image host on the next one).  
I'm sorry this issue is still happening for you! I'll keep trying to figure it out.

**Comment by 01brhodes** [comment]
my most recent craft was posted using kerbalx, so it did not use the discord linked images that some of my craft have. seems to be working fine.

**Comment by 01brhodes** [comment]
more craft pics arent working! and this time i used pics from imgur. pics seemed to work for a minute or so, before going to crashed spashe ship default. when clicked on, they show the desired image.
